server:
  port: 8080
neori:
  title: "Neori"
  version: 1
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/neoribd
    username: admin
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create