server:
  port: 8080
neori:
  title: "Neori"
  version: 1
spring:
  profiles:
    active: dev
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: admin
        url: jdbc:postgresql://dbpostgresql:5432/neoribd
        username: admin
        password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: create
#        show-sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect



